// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAQz7-QA_y4eFBnYT-koWYDX-eFZfKwgXA',
    appId: '1:65200996131:web:110e19fdd85dea4505d696',
    messagingSenderId: '65200996131',
    projectId: 'gymtec-2023',
    authDomain: 'gymtec-2023.firebaseapp.com',
    storageBucket: 'gymtec-2023.appspot.com',
    measurementId: 'G-PW4Z3KBTQ0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDN-z_1Vjxzt_f0aoWU2XwXT9nAkaNgGNA',
    appId: '1:65200996131:android:6e17938d71b210d505d696',
    messagingSenderId: '65200996131',
    projectId: 'gymtec-2023',
    storageBucket: 'gymtec-2023.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB3_M2j_J6TMe87QnXen7IgJoew4rLHCv8',
    appId: '1:65200996131:ios:d44583f7e206472505d696',
    messagingSenderId: '65200996131',
    projectId: 'gymtec-2023',
    storageBucket: 'gymtec-2023.appspot.com',
    iosClientId: '65200996131-04peih50iv4gv5fdrmjie6ic4adhk9lm.apps.googleusercontent.com',
    iosBundleId: 'com.example.gymTec',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB3_M2j_J6TMe87QnXen7IgJoew4rLHCv8',
    appId: '1:65200996131:ios:b6ac26d5d68c991905d696',
    messagingSenderId: '65200996131',
    projectId: 'gymtec-2023',
    storageBucket: 'gymtec-2023.appspot.com',
    iosClientId: '65200996131-sn4qfdbasos3leq9v9d8vl88nn2t0n45.apps.googleusercontent.com',
    iosBundleId: 'com.example.gymTec.RunnerTests',
  );
}
